# This workflow will build and deploy a web application to GitHub Pages
# Name of the workflow
# This workflow will build and deploy a web application to GitHub Pages
# Name of the workflow
name: Deploy to GitHub Pages

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches: [ "main" ] # Or your main branch name

# Allow this workflow to delete and create deployments
permissions:
  contents: read
  pages: write
  id-token: write

# A single job to perform the deployment
jobs:
  deploy:
    # The type of runner the job will run on
    runs-on: ubuntu-latest

    # Steps of the job
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js environment to build the app
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the React/Vite application
      - name: Build the app
        run: npm run build

      # Upload the built site as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # The path to the directory containing the deployment content
          artifact_name: github-pages

